stages:
  - build
  - test
  - deploy

services:
  - docker:dind

build-job:
  stage: build
  image: gradle:8.2-jdk17
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle_home
  script:
    - gradle clean build

test-job:
  stage: test
  image: gradle:8.2-jdk17
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle_home
  script:
    - gradle test

deploy-job:
  stage: deploy
  image: gitlab/dind
  script:
    - echo "docker build -t innobookingfakeapi ."
    - echo "docker run -p 8080:8080 innobookingfakeapi"
