stages:
  - build
  - deploy

image: gitlab/dind

services:
  - docker:dind

build-job:
  stage: build
  script:
    - docker build -t innobookingfakeapi .

deploy-job:
  stage: deploy
  script:
    - docker run -p 8080:8080 innobookingfakeapi
