stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - echo "docker build -t innobookingfakeapi ."

deploy-job:
  stage: deploy
  script:
    - echo " docker run -p 8080:8080 innobookingfakeapi"
